// <auto-generated />
using System;
using DawaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DawaAPI.Migrations
{
    [DbContext(typeof(QuranContext))]
    [Migration("20220430234444_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DawaAPI.Models.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdInSurah")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("SurahId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextEmlaey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextForHtml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurahId");

                    b.ToTable("Ayah");
                });

            modelBuilder.Entity("DawaAPI.Models.Explanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AyahId")
                        .HasColumnType("int");

                    b.Property<string>("ExplanationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("SourceId");

                    b.ToTable("Explanation");
                });

            modelBuilder.Entity("DawaAPI.Models.ExplanationSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExplanationSource");
                });

            modelBuilder.Entity("DawaAPI.Models.Surah", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("arabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("englishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("juza")
                        .HasColumnType("int");

                    b.Property<int>("numberOfPages")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Surah");
                });

            modelBuilder.Entity("DawaAPI.Models.Ayah", b =>
                {
                    b.HasOne("DawaAPI.Models.Surah", null)
                        .WithMany("ayat")
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DawaAPI.Models.Explanation", b =>
                {
                    b.HasOne("DawaAPI.Models.Ayah", "Ayah")
                        .WithMany("Explanations")
                        .HasForeignKey("AyahId");

                    b.HasOne("DawaAPI.Models.ExplanationSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });
#pragma warning restore 612, 618
        }
    }
}
