// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranKareem.Data;

namespace DawaAPI.Migrations
{
    [DbContext(typeof(QuranContext))]
    [Migration("20220426211041_DawaAPI")]
    partial class DawaAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuranKareem.Data.Models.Ayah", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idInSurah")
                        .HasColumnType("int");

                    b.Property<int>("pageNumber")
                        .HasColumnType("int");

                    b.Property<int>("surahId")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text_Emlaey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text_For_Html")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("surahId");

                    b.ToTable("Ayah");
                });

            modelBuilder.Entity("QuranKareem.Data.Models.Surah", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("arabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("englishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("juza")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Surah");
                });

            modelBuilder.Entity("QuranKareem.Data.Models.Ayah", b =>
                {
                    b.HasOne("QuranKareem.Data.Models.Surah", null)
                        .WithMany("ayat")
                        .HasForeignKey("surahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
