
USE [QURAN]
GO

/****** Object:  Table [dbo].[Surah]    Script Date: 9/18/2021 2:24:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Surah](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ArabicName] [nvarchar](14) NULL,
	[EnglishName] [nvarchar](14) NULL,
	[Juza] INT NOT NULL,
	[NumberOfPages] INT
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


